const types = {
  SEARCH_KEYWORD: "SEARCH_KEYWORD",
  SEARCH_MOVIES_REQUEST: "SEARCH_MOVIES_REQUEST",
  SEARCH_MOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCH_MOVIES_FAILURE: "SEARCH_MOVIES_FAILURE",
};

export default types;
